233 edit start time in Time Clock
ioet/time-tracker-ui pull request #552
Opened 2020-10-22 18:22 UTC by PaulRC-ioet

close #233

2020-10-22 18:55 UTC, Angeluz-07 requested changes
We also need to update values in summary.

2020-10-22 18:55 UTC, Angeluz-07 commented on src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
> +    this.store.dispatch(new entryActions.LoadActiveEntry());
It seems we also need to update Summary. Add the following line after line 121:
`this.store.dispatch(new entryActions.LoadEntriesSummary());`

2020-10-22 18:55 UTC, Angeluz-07 commented on src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
> +    this.store.dispatch(new entryActions.LoadActiveEntry());
Update tests accordingly.

2020-10-22 20:22 UTC, enriquezrene approved these changes

2020-10-23 19:10 UTC, Angeluz-07 approved these changes

2020-10-23 19:14 UTC, merged