refactor: TT-295 removal unnecessary feature toggles
ioet/time-tracker-ui pull request #706
Opened 2021-07-22 16:38 UTC by kevinjlope

**Problem**
Currently, there are some unnecessary feature toggles in the UI.
**Solution**
Removed feature toggles and the unit testing associated.

2021-07-23 13:10 UTC, JosueOb approved these changes
I already tried the local project and had no problem.

2021-07-23 18:19 UTC, PieritoAlva95 approved these changes
Very good work, keep up the good work 👍🏼 💯 🥇

2021-07-26 18:24 UTC, jase156 requested changes

2021-07-29 16:26 UTC, edgardavid2015 commented on src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
> -      this.newData.update_last_entry_if_overlap = true;
Done.

2021-07-29 16:27 UTC, edgardavid2015 commented on src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
> -      this.store.dispatch(new entryActions.UpdateCurrentOrLastEntry({ ...this.newData, ...this.entryForm.value }));
Done

2021-07-29 16:30 UTC, edgardavid2015 commented on src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.spec.ts
> +      featureManagerService.isToggleEnabledForUser = (toggleNameV) => of(param.bool);
Due to the error "no-shadowed-variable", the variable name changed adding the "V". Now that variable was deleted.

2021-07-30 17:01 UTC, jcalarcon98 approved these changes

2021-07-30 21:04 UTC, edgardavid2015 approved these changes

2021-08-02 15:38 UTC, jase156 approved these changes
Good Job Kevin and Edgar

2021-08-03 18:03 UTC, merged